### ISSUE TITLE
renku: show inputs in subfolder

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#437] opened 2019-03-01 09:38 UTC
**Describe the bug**
`renku show inputs` doesn't display files when called in subfolder.

--
might be needed for #436

**Comment by Panaetius** [comment] 2020-12-02 13:01
Verify this is still an issue

**Comment by Panaetius** [comment] 2020-12-09 09:54
```$ renku show inputs
input1
input2
$ cd data
$ renku show inputs
Warning: Run CLI commands only from project's root directory.

../input1
../input2
```
this works as intended, closing this issue.

**Closed by Panaetius** 2020-12-09 09:54 UTC
Labels: bug
