### ISSUE TITLE
cli: support workflow naming, listing, importing

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#223] opened 2018-06-28 13:36 UTC
```console
$ renku workflows/tools list/name/import
```

**Comment by rokroskar** [comment] 2018-07-31 09:57
This should probably include creation of metadata fields in the repo's metadata file.

**Comment by jirikuncar** [comment] 2018-08-22 13:46
We could go with following solutions:

1. Use `.renku/metadata.yml` for storing aliases for workflows/tools;
2. Add metadata inside workflows/tools CWL definition with name(s);
3. Create `.renku/refs/{workflows|tools}` with symlinks to generated files.

**Comment by Panaetius** [comment] 2021-06-07 13:10
Duplicate of https://github.com/SwissDataScienceCenter/renku-python/issues/1875

**Closed by Panaetius** 2021-06-07 13:10 UTC
Labels: workflow
