### ISSUE TITLE
CLI command for launching an interactive session locally

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1991] opened 2021-03-25 13:25 UTC
https://github.com/SwissDataScienceCenter/renku/pull/2043 adds some documentation for running renkulab images locally. The commands required to get a nice running session are a bit heavy and incomprehensible to most users - it would be helpful to have some CLI functionality to make this simpler for users. 

## A possible solution

Two commands:

Return the image name:commit for the current state of the project:

```
renku session image 

registry.<renku-host>/<namespace>/<project>:<commit-sha>
```

Start/stop a local docker container with the correct image for the current commit; if the image doesn't exist, build it first. If the session for this commit is already running, connect to it. 

```
renku session start/stop
```

One open question is what happens to the container logs - my opinion is that they should not be sent to the console by default but perhaps be available via another wrapper command.

**Comment by vigsterkr** [comment] 2021-12-09 09:37
duplicate of #2394

**Comment by rokroskar** [comment] 2021-12-09 09:39
isn't it the other way around? :)

**Comment by vigsterkr** [comment] 2021-12-09 09:40
does it matter?

**Closed** 2022-03-10 07:48 UTC
