### ISSUE TITLE
Provide alternative workflow runners

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1188] opened 2020-04-15 14:59 UTC
**Is your feature request related to a problem? Please describe.**

Currently, only the CWL reference runner is used to re-execute renku-generated workflows. Other runners exist, e.g. [Toil](https://toil.readthedocs.io/en/latest/#) and many others. Toil in particular can be used to execute CWL workflows through HPC batch queues, which is a feature some users are very interested in. We should investigate how to offer toil (or other runners) to the user. 

It may turn out that it's a better default option overall - it can, for example, parallelize parts of the DAG automatically even on a single machine. 

**Describe the solution you'd like**

something like

```bash
renku rerun --runner=toil <path>
```

**Describe alternatives you've considered**

using toil by hand.

**Comment by Panaetius** [comment] 2021-06-07 13:44
Duplicate of https://github.com/SwissDataScienceCenter/renku-python/issues/1875

**Closed by Panaetius** 2021-06-07 13:44 UTC
