### ISSUE TITLE
cli: renku dataset add CAMELS [...]

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#891] opened 2020-01-09 13:57 UTC
## Describe the bug
I try to add a large file directly by the link as data source. However, my memory fills up and I get the error below.  This is what I do:

```
renku dataset add CAMELS https://ral.ucar.edu/sites/default/files/public/product-tool/camels-catchment-attributes-and-meteorology-for-large-sample-studies-dataset-downloads/basin_timeseries_v1p2_modelOutput_daymet.zip
```

## Details
*Please verify and redact the details.*

**Renku version:** 0.8.3.dev12
**OS:** Linux (#201902061234 SMP Wed Feb 6 17:36:40 UTC 2019)
**Python:** 3.6.8

### Traceback

```
Traceback (most recent call last):
  File "[...]/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "[...]/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "[...]/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "[...]/requests/sessions.py", line 686, in send
    r.content
  File "[...]/requests/models.py", line 828, in content
    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
MemoryError
```

## Additional context
It is this new repository:
https://renkulab.io/gitlab/remko.nijzink/budyko

**Comment by rokroskar** [comment] 2020-01-09 15:37
Hi @rcnijzink thanks for the report - are you running this on renkulab or locally?

**Comment by rcnijzink** [comment] 2020-01-09 15:53
I did it first locally, I have 7.5 Gb of ram, then went to renkulab. The first time it failed, the second time it worked. In both cases I used 8G for the environment. The datafile itself is 4.2 Gb.

**Comment by mohammad-sdsc** [comment] 2020-01-10 08:20
Dear @rcnijzink, we've done some re-factoring recently (https://github.com/SwissDataScienceCenter/renku-python/pull/882) that got merged yesterday and should address this issue. I could add the link that you've provided in a VM with 2 GB of memory. Please upgrade to the latest version and try again and let us know if the issue is resolved or not.

**Comment by rcnijzink** [comment] 2020-01-10 08:35
Hi @mohammad-sdsc, I did:

```
pipx upgrade --pip-args=--pre renku
```

But is says I am already at the latest version 0.8.3.dev12. I tried anyway, but I got the same error. So is this the right version?

**Comment by mohammad-sdsc** [comment] 2020-01-10 09:25
No, it's not the latest version. Some tests on our side are failing and the latest version is not uploaded to the PyPI yet. Sorry about that, since I'm using the development repo I did not realise it. I'll let you know as soon as the issue is fixed.

**Comment by rokroskar** [comment] 2020-01-10 09:42
@rcnijzink you can upgrade to the master branch from source with `pipx`:

```
pipx upgrade --spec git+ssh://git@github.com/SwissDataScienceCenter/renku-python.git renku
```

**Comment by rcnijzink** [comment] 2020-01-10 14:37
@rokroskar, I get a permission error when I do that:

```
  ERROR: Command errored out with exit status 128:ataScienceCenter/renku-python.git#egg=renku'..
   command: git clone -q 'ssh://****@github.com/SwissDataScienceCenter/renku-python.git' /tmp/pip-install-__jswdw2/renku
       cwd: None
  Complete output (5 lines):
  git@github.com: Permission denied (publickey).
  fatal: Could not read from remote repository.
  
  Please make sure you have the correct access rights
  and the repository exists.
  ----------------------------------------
ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/SwissDataScienceCenter/renku-python.git' /tmp/pip-install-__jswdw2/renku Check the logs for full command output.
'~/.local/pipx/venvs/renku/bin/python -m pip install --upgrade git+ssh://git@github.com/SwissDataScienceCenter/renku-python.git#egg=renku -q' failed

```

**Comment by rokroskar** [comment] 2020-01-10 15:41
oh sorry, if you don't have an ssh key set up with github you can clone over https:

```
pipx upgrade --spec https://github.com/SwissDataScienceCenter/renku-python.git renku
```

**Comment by rcnijzink** [comment] 2020-01-10 16:01
Yes, it worked now and I added the dataset, thanks!

**Comment by rokroskar** [comment] 2020-01-29 16:07
Hey @rcnijzink just wondering if we can close this?

**Closed** 2020-02-13 15:54 UTC
