### ISSUE TITLE
Renku --isolation fails with empty outputfolder 

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#582] opened 2019-07-05 12:53 UTC
**Describe the bug**
When running 

```
renku run --isolation bash src_sh/run_vom2.sh VOM/VOM_Fortran/ data/VOM_input/ data/VOM_output/2/ work/HowardSprings/freedrainage_cpcff1.0/vom_namelist
```

it fails as the folder data/VOM_output/2 is empty and is not cloned for running it in isolation. 

**To Reproduce**
I did this in this repo:
https://renkulab.io/gitlab/remko.nijzink/wave_demo

**Expected behavior**
That the outputfolder is still found, also in isolation. I fixes it now by adding a dummy-file to the folder and commit. 

**Desktop (please complete the following information):**
Ubuntu 18.04.2 LTS

**Comment by ableuler** [comment] 2019-09-10 15:09
Hi @rcnijzink,

thanks for reporting this issue and sorry for the late response. The problem is that `renku run --isolation` checks out your repo in a separate [worktree](https://git-scm.com/docs/git-worktree). Since the empty folder is not part of the repo, a checkout will not result in this directory being created. As you have noticed, git does not allow you to add an empty directory to your repository, so adding an empty dummy file (for example `.gitkeep`) is actually the recommended way of adding an "empty" directory in cases where the directory structure itself is important.
The cleaner option for your problem in my opinion would be to create the output directory as part of your script in case it does not exist.

Every way of "fixing" this git behaviour through Renku seems very cumbersome and hacky to me, I will thus close this issue.

**Closed by ableuler** 2019-09-10 15:09 UTC
