### ISSUE TITLE
Enable RenkuLab login through the CLI

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-python#1242] opened 2020-05-04 13:11 UTC
In the future there will be more and more cases where the Renku CLI needs to access the RenkuLab API (first and foremost for the purpose of querying the Renku knowledge graph). For this purpose, the CLI needs a mechanism to acquire a JWT on behalf of the user allowing it to query the API through the gateway.

**Comment by Panaetius** [comment] 2020-12-04 08:29
Duplicate of https://github.com/SwissDataScienceCenter/renku-python/issues/677

**Closed by Panaetius** 2020-12-04 08:29 UTC
