### ISSUE TITLE
Setting sessions server options does not always work

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-python#2314] opened 2021-09-06 19:43 UTC
**Describe the bug**
Changing the default server options does not seems to work on some projects. The change is shown in the UI as if it succeeds. But there is no commit in the repo.

**Link to project**
https://renkulab.io/projects/tasko.olevski/maristem-omics-2

**To Reproduce**
1. Fork https://renkulab.io/projects/tasko.olevski/maristem-omics-2
2. Try to change the server options for the sessions (i.e. settings -> sessions)
3. Check the commits in the repo and/or the renku.ini file. The new settings are not persisted as expected.

**Expected behavior**
Changing the settings should be persisted.

**Run environment (please complete the following information):**
 - renku-python version - 0.16.0
 - Python version - 3.7
 - local terminal OR renkulab interactive environment? - renkulab

**Additional context**
Tried to replicate this from a fresh project and could not. So it is something specific with the project I link here.

**Comment by Panaetius** [comment] 2021-09-10 07:15
Looking into this a bit, it seems the cause is the same as the one reported in  https://github.com/gitpython-developers/GitPython/issues/890 , so something with symlinks to submodules (or because the renku service only does a very shallow clone, I think without submodules).

Could this apply in your project?

For reference, event 7b634698cb814deaa856b5734fb30321 in sentry points to this.

**Comment by Panaetius** [comment] 2021-09-10 09:32
I wanted to check if we can at least propagate the error properly so a users knows something is wrong, but it's swallowed by GitPython and we just get a return from their methods as if they passed, e.g. a git diff in GitPython will return `[]` and just print the error to stderr instead of raising.

So there's no way for us to catch the error and from what I see also nothing to do to fix it on our side.

I think if you just had 1 submodule and linked to the files there instead of adding the same submodule twice with paths, it could work.

**Comment by Panaetius** [comment] 2021-11-17 13:50
Closing this as it's out of our hands and gitpython doesn't give us any way of dealing with it

**Closed by Panaetius** 2021-11-17 13:50 UTC
