### ISSUE TITLE
Renku update fails with scala kernel

### ISSUE THREAD

**Issue by joke1196** [SwissDataScienceCenter/renku-python#1671] opened 2020-11-02 09:22 UTC
**Describe the bug**
When using `renku update` on a jupyter notebook which uses a scala kernel, the process fails with: `jupyter_client.kernelspec.NoSuchKernel: No such kernel named scala`. This happens even though `renku run` succeeded previously.

**Link to project**
https://dev.renku.ch/projects/renku-qa/coffee-orders/

**To Reproduce**
1. Connect to the jupyter hub environment of the project
2. In a terminal window execute the command `renku run papermill src/Coffee_orders.ipynb src/Coffee_orders_output.ipynb -p numberOfOrderChallenge 35000`
3. Change something in the file `src/Coffee_order.ipynb` for example change `val challengersByLocation = potentialWinner.reverse.takeWhile{ case( _, coffeeSold) => coffeeSold >= numOfOrderChallenge }.take(3)` to `val challengersByLocation = potentialWinner.reverse.takeWhile{ case( _, coffeeSold) => coffeeSold >= numOfOrderChallenge }.take(5)`
4. Commit the change
5. Execute the command `renku update`
6. See the error 

**Expected behavior**
The command should succeed and change the content of the file in `output/test_notebook.txt`

**Screenshots and/or execution output**
This is the output error 
`Resolved '../../tmp/tmp1x8pm6q8/0814d53a-90de-4c8b-89f3-58cac7f95610.cwl' to 'file:///tmp/tmp1x8pm6q8/0814d53a-90de-4c8b-89f3-58cac7f95610.cwl'
INFO:cwltool:Resolved '../../tmp/tmp1x8pm6q8/0814d53a-90de-4c8b-89f3-58cac7f95610.cwl' to 'file:///tmp/tmp1x8pm6q8/0814d53a-90de-4c8b-89f3-58cac7f95610.cwl'
[job 3b627558-6778-49c7-893e-b0d252c380fd] /tmp/ol517alo$ papermill \
    /tmp/ol517alo/src/Coffee_orders.ipynb \
    src/Coffee_orders_output.ipynb \
    -p \
    numberOfOrderChallenge \
    35000
INFO:cwltool:[job 3b627558-6778-49c7-893e-b0d252c380fd] /tmp/ol517alo$ papermill \
    /tmp/ol517alo/src/Coffee_orders.ipynb \
    src/Coffee_orders_output.ipynb \
    -p \
    numberOfOrderChallenge \
    35000
Input Notebook:  /tmp/ol517alo/src/Coffee_orders.ipynb
Output Notebook: src/Coffee_orders_output.ipynb
Executing:   0%|                                                                                                                                                           | 0/6 [00:00<?, ?cell/s]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/papermill/cli.py", line 256, in papermill
    execution_timeout=execution_timeout,
  File "/opt/conda/lib/python3.7/site-packages/papermill/execute.py", line 106, in execute_notebook
    **engine_kwargs
  File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 49, in execute_notebook_with_engine
    return self.get_engine(engine_name).execute_notebook(nb, kernel_name, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 343, in execute_notebook
    cls.execute_managed_notebook(nb_man, kernel_name, log_output=log_output, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/papermill/engines.py", line 402, in execute_managed_notebook
    return PapermillNotebookClient(nb_man, **final_kwargs).execute()
  File "/opt/conda/lib/python3.7/site-packages/papermill/clientwrap.py", line 43, in execute
    with self.setup_kernel(**kwargs):
  File "/opt/conda/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 438, in setup_kernel
    self.start_new_kernel(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.7/site-packages/nbclient/client.py", line 394, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "/opt/conda/lib/python3.7/site-packages/nbclient/util.py", line 85, in ensure_async
    result = await obj
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 571, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 262, in pre_start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 181, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/manager.py", line 87, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/opt/conda/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 235, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named scala
[job 3b627558-6778-49c7-893e-b0d252c380fd] completed permanentFail
WARNING:cwltool:[job 3b627558-6778-49c7-893e-b0d252c380fd] completed permanentFail
Error: Unable to finish re-executing workflow; check the workflow execution outline above and the generated /tmp/tmp1x8pm6q8/0814d53a-90de-4c8b-89f3-58cac7f95610.cwl file for potential issues, then remove the /tmp/tmp1x8pm6q8/0814d53a-90de-4c8b-89f3-58cac7f95610.cwl file and try again` 

**Run environment (please complete the following information):**
 - renku-python version 0.11.6
 - Python 3.7.6
 - renku interactive environment on DEV
 - Jupyterlab & browser firefox

**Additional context**
I tried to add a kernel for scala on this project, with the almond project: https://almond.sh

**Comment by Panaetius** [comment] 2021-03-03 08:51
I'm not sure in this exact case, still looking into it, but usually the issue is that `renku` gets installed with pipx in a different virtualenv than the regular environment, so when renku update call cwl to reexecute a workflow, it's in a different venv and there the relevant kernels are not installed.

**Comment by Panaetius** [comment] 2021-03-04 09:12
I couldn't reproduce this issue due to the coffee emoji in the `coffee-orders-:coffee:-by-location` filename, which doesn't work for me on Jupyterlab (I discussed this issue with UI) and having to rewrite the history of the repository if I wanted to change this filename (since it's used in some dependent workflows). I created an issue for unicode support in renku-python.

But I think what it boils down to is:
```
$ renku run jupyter kernelspec list > kernels.txt
$  cat kernels.txt 
Available kernels:
  scala      /home/jovyan/.local/share/jupyter/kernels/scala
  python3    /opt/conda/share/jupyter/kernels/python3
$  renku rerun kernels.txt 
Resolved '../../tmp/tmpc1jh3jdk/c8aa83ff-c696-4981-b743-bce626fc4f74.cwl' to 'file:///tmp/tmpc1jh3jdk/c8aa83ff-c696-4981-b743-bce626fc4f74.cwl'
INFO:cwltool:Resolved '../../tmp/tmpc1jh3jdk/c8aa83ff-c696-4981-b743-bce626fc4f74.cwl' to 'file:///tmp/tmpc1jh3jdk/c8aa83ff-c696-4981-b743-bce626fc4f74.cwl'
[job b2920293-5c96-4388-bf36-b1790659b3ee] /tmp/7dwqcyx8$ jupyter \
    kernelspec \
    list > /tmp/7dwqcyx8/kernels.txt
INFO:cwltool:[job b2920293-5c96-4388-bf36-b1790659b3ee] /tmp/7dwqcyx8$ jupyter \
    kernelspec \
    list > /tmp/7dwqcyx8/kernels.txt
[job b2920293-5c96-4388-bf36-b1790659b3ee] completed success
INFO:cwltool:[job b2920293-5c96-4388-bf36-b1790659b3ee] completed success
$  cat kernels.txt 
Available kernels:
  python3    /opt/conda/share/jupyter/kernels/python3
```

or more specifically:
```
$  renku run jupyter --data-dir > datadir.txt
$  cat datadir.txt
/home/jovyan/.local/share/jupyter
$  renku rerun datadir.txt
Resolved '../../tmp/tmpk5ak6xd0/a0c1250b-3c56-493f-aabb-861d36d97379.cwl' to 'file:///tmp/tmpk5ak6xd0/a0c1250b-3c56-493f-aabb-861d36d97379.cwl'
INFO:cwltool:Resolved '../../tmp/tmpk5ak6xd0/a0c1250b-3c56-493f-aabb-861d36d97379.cwl' to 'file:///tmp/tmpk5ak6xd0/a0c1250b-3c56-493f-aabb-861d36d97379.cwl'
[job 26e413e4-f05c-4083-8786-b5903f8d2cd8] /tmp/rctabpr6$ jupyter \
    --data-dir > /tmp/rctabpr6/datadir.txt
INFO:cwltool:[job 26e413e4-f05c-4083-8786-b5903f8d2cd8] /tmp/rctabpr6$ jupyter \
    --data-dir > /tmp/rctabpr6/datadir.txt
[job 26e413e4-f05c-4083-8786-b5903f8d2cd8] completed success
INFO:cwltool:[job 26e413e4-f05c-4083-8786-b5903f8d2cd8] completed success
$ cat datadir.txt
/tmp/rctabpr6/.local/share/jupyter
```

When we use cwltool to execute a workflow, we tell it to preserver all environment variables, so you'd expect `$HOME` to be carried over, but unfortunately, that is not the case. If you take a look at https://github.com/common-workflow-language/cwltool/blob/70dafe0d36ac40246cb2629c08993e68ef36165d/cwltool/job.py#L551 it has $HOME hard-coded to the temporary directory the workflow gets executed in. And jupyter uses this to find installed kernels, so it breaks on rerun/update. I don't see a way that we can fix this on our end, as it might break other things in cwltool.

Two solutions do come to mind:
- Install the kernel globally (e.g. `./coursier launch --fork almond -- --install --global`
- Add `/home/jovyan/.local/` as an explicit input to the workflow (then it gets copied over into the tmp directory). Though this would have the side-effect of re-executing everything if a change happens in  `/home/jovyan/.local/`

I will close this issue as there's not really anything we can do on our side. Hopefully once we support other workflow runners, this will be a non-issue.

**Closed by Panaetius** 2021-03-04 09:12 UTC
Labels: QA
