### ISSUE TITLE
renku init --no-external-storage should be more explicit

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#562] opened 2019-06-25 20:56 UTC
**Describe the bug**
If git lfs is enabled in a global config, `renku init --no-external-storage` will not prevent files from being added to LFS. Currently it does not *install* LFS but it also does not prevent LFS from being used if it is enabled in a higher-level config. It should instead run `git lfs install --skip-smudge --local`

**Comment by mohammad-sdsc** [comment] 2019-07-01 15:05
I don't understand the proposed solution here: `git lfs install --skip-smudge --local`. This does not prevent *adding* of files to LFS and only avoid automatic downloading of LFS files when pulling or cloning.

**Comment by rokroskar** [comment] 2019-07-01 15:22
No, running `git lfs install --skip-smudge --local` results in this `.git/config`:

```
[filter "lfs"]
        required = true
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge --skip -- %f
        process = git-lfs filter-process --skip
```

**Comment by rokroskar** [comment] 2019-07-01 15:38
Actually I think the `--no-local-storage` option is just broken for some reason - even if I don't have git-lfs installed anywhere and I initialize the repo with the `-S` option it still tries to put outputs in LFS.

**Comment by mohammad-sdsc** [comment] 2019-07-01 16:07
Exactly, I've tried with different LFS variation (i.e. --skip-smudge added to local, user, and system's .gitconfig) and it still add files to LFS.

**Comment by mohammad-sdsc** [comment] 2019-07-01 16:12
```
$ git lfs install --help

...
* --skip-smudge:
    Skips automatic downloading of objects on clone or pull. This requires a
    manual "git lfs pull" every time a new commit is checked out on your
    repository.
...
```

**Comment by mohammad-sdsc** [comment] 2019-07-02 07:22
The problem is that when at the project creation time we provide the `--no-external-storage`, it is not persisted in the renku project file (if such a thing exist). Therefore, when we call the next command, renku has no idea that it shouldn't use LFS.

**Comment by jsam** [comment] 2019-07-02 09:48
The way how you can know that repo is initialized with `--no-external-storage` flag is by looking at .git/config and searching for LFS section. If there is no such section there, you know that repo was initialized with `--no-external-storage`. 

There is `.renku/metadata.yml` file if you need to persist certain options, but I'm not sure if we should persist this one since it could lead to inconsistency with git.

**Comment by rokroskar** [comment] 2019-07-02 11:09
The thing is that renku-python should *already* be doing this check. 

Maybe https://github.com/SwissDataScienceCenter/renku-python/blob/ae67be74587a181e6a3c83cdf07ecbc082e58a06/renku/api/storage.py#L62 needs to specifically check the local instead of global configuration.

**Comment by mohammad-sdsc** [comment] 2019-07-02 11:28
In that code, when calling `self.repo.config_reader()` with no parameter it checks the config for the repo and all higher configs (i.e. user and system). This is fixed by passing the desired level to it: `self.repo.config_reader(config_level="repository").

I am fixing this.

**Closed** 2019-07-11 09:11 UTC
Labels: bug, good first issue
