### ISSUE TITLE
cwl: support scatter

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#310] opened 2018-10-04 08:06 UTC
**Is your feature request related to a problem? Please describe.**

Process multiple files from a directory.

**Describe the solution you'd like**

Apply tool on multiple inputs (https://github.com/Gibbsdavidl/CWL_scatter_example).

**Describe alternatives you've considered**

Use git branches and merge.

**Comment by jirikuncar** [comment] 2019-04-09 09:17
```
renku foreach NAME --glob="inputs/*.txt" run python {NAME} outputs/{NAME}.pdf
```

**Comment by Panaetius** [comment] 2021-06-07 13:11
Duplicate of https://github.com/SwissDataScienceCenter/renku-python/issues/1875

**Closed by Panaetius** 2021-06-07 13:11 UTC
