### ISSUE TITLE
fix(service): dataset import failed due to HookExecutionError

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1429] opened 2020-07-31 06:32 UTC
For the following job:
```
renku.service.jobs.datasets.dataset_import({'user_id': '009add8c-2ff9-4d70-87a4-c0537c27f0b8', 'token': '9b6ca0b120ad2ed3972ae0a50cbb6639593ceeb831ecb2c512300ea2ca826711', 'fullname': 'Rok Roskar', 'email': 'rok.roskar@sdsc.ethz.ch'}, 'a5b515ac45b1450d85669b6f54502e09', '8cd507077373422eb2930068abea13c9', 'https://zenodo.org/record/3950074', extract=False, short_name=None, timeout=1800)
```

we are receiving following stacktrace
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 883, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 640, in perform
    self._result = self._execute()
  File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 646, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/code/renku/renku/service/views/decorators.py", line 86, in decorated_function
    return f(cache, *args, **kwargs)
  File "/code/renku/renku/service/jobs/datasets.py", line 88, in dataset_import
    progress=DatasetImportJobProcess(cache, user_job)
  File "/code/renku/renku/core/commands/client.py", line 103, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/code/renku/renku/core/commands/dataset.py", line 655, in import_dataset
    total_size=total_size,
  File "/code/renku/renku/core/commands/dataset.py", line 287, in add_to_dataset
    progress=progress,
  File "/code/renku/renku/core/management/datasets.py", line 421, in add_data_to_dataset
    self.repo.index.commit(msg, skip_hooks=skip_hooks)
  File "/usr/local/lib/python3.7/site-packages/git/index/base.py", line 944, in commit
    run_commit_hook('pre-commit', self)
  File "/usr/local/lib/python3.7/site-packages/git/index/fun.py", line 95, in run_commit_hook
    raise HookExecutionError(hp, cmd.returncode, stderr, stdout)
git.exc.HookExecutionError: Hook('/svc/cache/projects/009add8c-2ff9-4d70-87a4-c0537c27f0b8/rok.roskar/test-datasets/.git/hooks/pre-commit') failed due to: exit code(1)
  cmdline: /svc/cache/projects/009add8c-2ff9-4d70-87a4-c0537c27f0b8/rok.roskar/test-datasets/.git/hooks/pre-commit
  stdout: 'You are trying to commit large files to Git instead of Git-LFS.

Large files:
You are using renku version 0.10.5.dev0+dirty, however version 0.10.5 is available.
You should consider upgrading ...

To track these files in Git LFS use "git lfs track <FILENAMES>".

To commit anyway, use "git commit --no-verify".
'
```

**Comment by Panaetius** [comment] 2020-08-03 15:47
Duplicate of https://github.com/SwissDataScienceCenter/renku-python/issues/1257 , closing this. Will be in next release.

**Closed by Panaetius** 2020-08-03 15:47 UTC
