### ISSUE TITLE
Collections within Collections are not serialized correctly

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1360] opened 2020-07-02 14:46 UTC
**Describe the bug**
When a workflow has a `Collection` within a `Collection`, it is serialized as an `Entity` and its members and type are lost.

**To Reproduce**
Checkout `renku-python` commit related to save and load workflows as jsonld: `git checkout d403289c`

```
git clone https://renkulab.io/gitlab/alisafaee/covid-19-public-data.git
cd covid-19-public-data
git checkout 4d69104ce15dc91496a2f555b17a8a938072a85b
python3 -c 'from renku.core.models.provenance.activities import WorkflowRun ; WorkflowRun.from_yaml(".renku/workflow/00d7a5f7e44344088b98d2119a26f817_migrated.yaml").to_yaml()'
git diff
```

**Comment by Panaetius** [comment] 2020-07-29 11:54
Needs testing if this still exists after the calamus changes in https://github.com/SwissDataScienceCenter/renku-python/pull/1386

**Comment by Panaetius** [comment] 2020-07-30 12:24
I tested this with the calamus workflows PR and couldn't reproduce this, closing this issue.

**Closed by Panaetius** 2020-07-30 12:24 UTC
