### ISSUE TITLE
Renku Workflow Visualize --interactive: curses returned null

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-python#3266] opened 2023-01-16 18:46 UTC
**Describe the bug**
I tried to run `renku workflow visualize <> --interactive` in my project, and got an error. `renku workflow visualize <>` works just fine. The workflows were ran via Workflow Files. There are 6 steps in total.

## Details
**Renku version:** 2.0.1.dev20+gc18ccda
**OS:** Linux (#58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022)
**Python:** 3.9.12

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/renku/ui/cli/exception_handler.py", line 133, in main
    return super().main(*args, **kwargs)
  File "[...]/site-packages/renku/ui/cli/exception_handler.py", line 92, in main
    return super().main(*args, **kwargs)
  File "[...]/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "[...]/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "[...]/site-packages/renku/ui/cli/workflow.py", line 1290, in visualize
    viewer.run()
  File "[...]/site-packages/renku/ui/cli/utils/curses.py", line 346, in run
    curses.wrapper(self._main)
  File "[...]/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "[...]/site-packages/renku/ui/cli/utils/curses.py", line 341, in _main
    self._init_curses(screen)
  File "[...]/site-packages/renku/ui/cli/utils/curses.py", line 92, in _init_curses
    self.content_pad = curses.newpad(self.content_max_y, self.content_max_x)
_curses.error: curses function returned NULL
```
 
**Link to project**
https://ci-renku-2901.dev.renku.ch/projects/laura.kinkead/academic-team-demo-sklearn/workflows/e5b50508f443a8ba4e76597a84116b0f

But this is my presentation demo project, so please careful not to edit it!

**To Reproduce**
1. `renku workflow visualize data/05_metrics/model_comparison.png --interactive`

**Expected behavior**
Workflow visualize in interactive mode to start

**Screenshots and/or execution output**
If it matters, my workflow is quite big- this is what it looks like without visualize. But that's exactly why I want the interactive mode!

![image](https://user-images.githubusercontent.com/7387902/212747464-56f7ad6c-2b1b-45cb-aa68-2374b2710468.png)

**Comment by Panaetius** [comment] 2023-01-24 08:10
Duplicate of https://github.com/SwissDataScienceCenter/renku-python/issues/3242

**Closed by Panaetius** 2023-01-24 08:10 UTC
Labels: bug
