### ISSUE TITLE
Dataset add overrides existing files in a dataset

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#884] opened 2019-12-23 14:16 UTC
Let's say we have a following use case:

```
renku dataset create ds1
renku dataset add ds1 ../data1/datafile
renku dataset add ds1 ../data2/datafile
```

In this scenario, as a user I would expect that now I have 2 files in a dataset since (beside the name) data files are different. Current behavior is that renku add overrides the previous record silently.

As a user I would expect that second add fails with a error or that we succeed with an add operation.

**Comment by mohammad-sdsc** [comment] 2020-01-16 10:25
I cannot reproduce this. When adding a file with the same name the following error is printed:
```
Error: File already exists in dataset. Use --force to add.
```
It seems to be fixed by https://github.com/SwissDataScienceCenter/renku-python/pull/877

**Closed by mohammad-sdsc** 2020-01-16 10:25 UTC
