### ISSUE TITLE
renku dataset import leads to missing objects

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#1337] opened 2020-06-19 08:00 UTC
**Describe the bug**
I imported a dataset, and this works nicely, but the files that are added are just the lfs-pointers. Pulling them with lfs leads to an error. 

**Link to project**
https://renkulab.io/projects/remko.nijzink/budyko

**To Reproduce**
I imported a dataset like this:

```
renku dataset import https://renkulab.io/datasets/3ada2727-8ef6-4c3e-8873-d33109970636
```
When I try to do ```git lfs pull ``` it gives me an error.

**Expected behavior**
That the actual files are added somewhere. 

**Screenshots and/or execution output**
This is the error I get:

```
Git LFS: (0 of 0 files, 12 skipped) 0 B / 0 B, 1.13 MB skipped                                                                      [0bb9fcca32b4d1675a8db185d36400075663f1035521f6a1400fa00ab00e5cd5] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[d5846b1c4a0f47610fbe1653cbb9a3a59f33048386b0b84288b6e76cae06fb24] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[937626ca5dd96d11e6d94bf1e2c2f12b9adef24147bfe84582f7bb9d9d5f8345] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[6ec726f8e0b61cc266790e7146adc37fb77e8d515f5b02ceaf7ceafe9ba03e9e] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[b9d4bb49963bc9a02f72c5e62b61916c328cc68116496d0c8b51bfbc4e2bbe50] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[fe6a3c8c7e69b537034eb04f73242ac5ae837c75809612ac5e68218b1dc59da2] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[87f1f2aa67639a6840e1c24bc6ac464c38120d411ca8ebbeccb90db0712236b1] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[25a28322a24aa1e30778e75d8fae498e6e3aec428a076c98245c2542cad3370f] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[5c58b3fd30aae99c77fcc41f36acf37b9c7efe0184ff56505b9065abaad865b3] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[6a1e77e140e363026dce597444209f4af0baeb4c5e72d1fd4226bcce18203a8a] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[2c5f745757d76326b0ee041e0b2a20482d024180e25c5ba18a52d420ea23ae08] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
[21dcc05f4a7753f733783c7b0ddbff3b61f9cd5d7705ca587b9ec573039829d8] Object does not exist on the server or you don't have permissions to access it: [404] Object does not exist on the server or you don't have permissions to access it
error: failed to fetch some objects from 'https://renkulab.io/remko.nijzink/budyko.git/info/lfs'
```

**Run environment (please complete the following information):**
Renku version: 0.10.5.dev21
OS: Linux 
Python: 3.6.9

**Comment by rokroskar** [comment] 2020-06-26 15:18
Hi @rcnijzink did you push the repo after you did the import?

**Comment by rcnijzink** [comment] 2020-06-26 15:27
Ah sorry, but the push kept failing because of the missing lfs-files. So I rolled back, manually downloaded the files from the other repo and did  ```renku dataset add DINGO path_to_local_files```.

**Comment by mohammad-sdsc** [comment] 2020-07-07 10:21
Hi @rcnijzink 
I cloned your project but I could not re-produce this problem. The import worked fine for me and all files were pulled from the remote storage. It even works when LFS smudge filter is disabled (i.e. `export GIT_LFS_SKIP_SMUDGE=1`).
```
[~/playground/budyko]$ renku dataset import https://renkulab.io/datasets/3ada2727-8ef6-4c3e-8873-d33109970636 --short-name DINGO-2
CHECKSUM                                  NAME                     SIZE (MB)  TYPE
----------------------------------------  ---------------------  -----------  ------
bbef48bcf22f277632ba7b64d6cf2f6f78b1ca00  Ea_adelaide.txt               0.02  txt
850eefa136dc5ce8578fcfcc939e8f277e3cd70d  Ea_daly.txt                   0.12  txt
bd3c5efddac4960213fa84574cb05542749b1692  Ea_dry.txt                    0.10  txt
402fa03e1947f7f371795fc820f85bf978c3a5ec  Ea_howard.txt                 0.18  txt
827df66c446d3393c8a3abf8d4607c32ec3ee9b2  Ea_litch.txt                  0.07  txt
9d10f8b832b356c22132fa684980c0e1c09c843f  Ea_sturt.txt                  0.10  txt
9eee278f7d16df5f722f70f7f5e612a1f1222dc0  GPPdaily_adelaide.txt         0.02  txt
8c07f06a5f0f5a0e6ec1983c6a577a5c4dfd29e0  GPPdaily_daly.txt             0.12  txt
1469d0f7c89421496f7fa02caefb167ee431a299  GPPdaily_dry.txt              0.10  txt
f9b3ac0ed05be7922b93ff96a5d9cce0de1d610b  GPPdaily_howard.txt           0.18  txt
0b891466247bab1d285dc9f789234bbe73893066  GPPdaily_litch.txt            0.07  txt
34627f02d2de5844c92d300c5f8c5e68f4c85c74  GPPdaily_sturt.txt            0.10  txt
Do you wish to download this version? [y/N]: y
Info: Adding these files to Git LFS: 66 KB | 0 B/s                                                                                                              
        data/DINGO-2/GPPdaily_dry.txt
        data/DINGO-2/Ea_daly.txt
        data/DINGO-2/GPPdaily_sturt.txt
        data/DINGO-2/GPPdaily_daly.txt
        data/DINGO-2/GPPdaily_howard.txt
        data/DINGO-2/Ea_dry.txt
        data/DINGO-2/Ea_howard.txt
        data/DINGO-2/Ea_sturt.txt
To disable this message in the future, run:
        renku config show_lfs_message False
OK                                                                             
[~/playground/budyko]$ tail data/DINGO-2/GPPdaily_dry.txt
 2018-03-13 00:00:00   -0.47
 2018-03-14 00:00:00   -0.46
 2018-03-15 00:00:00   -0.40
 2018-03-16 00:00:00   -0.46
 2018-03-17 00:00:00   -0.37
 2018-03-18 00:00:00   -0.47
 2018-03-19 00:00:00   -0.47
 2018-03-20 00:00:00   -0.44
 2018-03-21 00:00:00   -0.44
 2018-03-22 00:00:00   -0.18
```

I was using renku `v0.10.4`. Can you try with this version and see if it works?

**Comment by rcnijzink** [comment] 2020-07-07 12:32
No, it doesn't work unfortunately, this is what happens:

```
Error: unknown flag: --name-only

Error: unknown flag: --name-only

Error: unknown flag: --name-only

Error: unknown flag: --name-only

Error: unknown flag: --name-only

Error: unknown flag: --name-only

Error: unknown flag: --name-only

Error: unknown flag: --name-only

Error: unknown flag: --name-only

Error: unknown flag: --name-only

Error: unknown flag: --name-only

Error: unknown flag: --name-only

CHECKSUM                                  NAME                     SIZE (MB)  TYPE
----------------------------------------  ---------------------  -----------  ------
bbef48bcf22f277632ba7b64d6cf2f6f78b1ca00  Ea_adelaide.txt               0.00  txt
850eefa136dc5ce8578fcfcc939e8f277e3cd70d  Ea_daly.txt                   0.00  txt
bd3c5efddac4960213fa84574cb05542749b1692  Ea_dry.txt                    0.00  txt
402fa03e1947f7f371795fc820f85bf978c3a5ec  Ea_howard.txt                 0.00  txt
827df66c446d3393c8a3abf8d4607c32ec3ee9b2  Ea_litch.txt                  0.00  txt
9d10f8b832b356c22132fa684980c0e1c09c843f  Ea_sturt.txt                  0.00  txt
9eee278f7d16df5f722f70f7f5e612a1f1222dc0  GPPdaily_adelaide.txt         0.00  txt
8c07f06a5f0f5a0e6ec1983c6a577a5c4dfd29e0  GPPdaily_daly.txt             0.00  txt
1469d0f7c89421496f7fa02caefb167ee431a299  GPPdaily_dry.txt              0.00  txt
f9b3ac0ed05be7922b93ff96a5d9cce0de1d610b  GPPdaily_howard.txt           0.00  txt
0b891466247bab1d285dc9f789234bbe73893066  GPPdaily_litch.txt            0.00  txt
34627f02d2de5844c92d300c5f8c5e68f4c85c74  GPPdaily_sturt.txt            0.00  txt
Do you wish to download this version? [y/N]: y
Error: unknown flag: --name-only

OK           
```            

So it already says the size is 0 MB and there is something about an unkown flag, that I am not using at all. I tried it with renku v0.10.4 and 0.10.5.dev21

**Comment by rokroskar** [comment] 2020-07-07 12:33
How are you installing the different versions?

**Comment by rcnijzink** [comment] 2020-07-07 12:39
I installed v0.10.4 in a conda environment for testing, and used pip install there. I installed 0.10.5.dev21 a few weeks ago, and I'm not entirely sure, but believe it was like this:

```
pipx upgrade --pip-args=--pre renku
```

**Comment by mohammad-sdsc** [comment] 2020-07-07 14:28
`Error: unknown flag: --name-only`  comes from Git FLS. Your LFS version does not support this flag. Please try to update it if possible.

**Comment by rokroskar** [comment] 2020-07-07 14:33
I also can't reproduce this - I tried with both of those versions, it works in both cases. I installed it with 

```
pipx install --force renku==0.10.4
```

```
pipx --version
0.15.1.3

~/.local/pipx/shared/bin/pip --version
pip 20.1.1

git lfs --version
git-lfs/2.10.0 (GitHub; darwin amd64; go 1.13.6)

git --version
git version 2.21.0
```

**Comment by rcnijzink** [comment] 2020-07-07 14:44
Ah thanks, updating lfs made it work!

**Comment by rokroskar** [comment] 2020-07-07 14:45
@mohammad-sdsc do you know which version of git-lfs introduced that flag? We should be clear(er) in our requirements...

**Comment by mohammad-sdsc** [comment] 2020-07-07 14:57
Nothing in their changlog but based on the git history it in from at least `v2.6.0`. Actually, it was renamed from `--name`.

**Comment by rokroskar** [comment] 2020-07-07 15:05
I suggest we close this and follow up with a change to the README that clearly states which version of git-lfs is required

**Closed** 2020-07-22 08:02 UTC
Labels: bug, user
