### ISSUE TITLE
Bug with renku update?

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-python#827] opened 2019-11-19 04:34 UTC
## Describe the bug

Trying to `run renku` update after editing `outputs/simdata.csv`.

The KG display looks intriguing:

```
renku run Rscript src/simulate.R outputs/simdata.csv
renku run Rscript src/plot.R --input outputs/simdata.csv --output outputs/plot.pdf
renku run Rscript src/estimate.R --input outputs/simdata.csv --output outputs/estimate.Rout
```
I ran the commands 3 times and I see:
https://renkulab.io/projects/1383/files/lineage/src/estimate.R
![image](https://user-images.githubusercontent.com/4173925/69116786-8f422580-0a5b-11ea-98a6-3115351c4d3a.png)

Is it for all the renku runs?  Because there's actually only one file:

![image](https://user-images.githubusercontent.com/4173925/69116816-ab45c700-0a5b-11ea-8207-d2e2a757e4b9.png)

## Details

**Renku version:** 0.5.2
**OS:** Linux (#1 SMP Mon Oct 22 10:40:32 EDT 2018)
**Python:** 3.7.4

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/cli/_exc.py", line 100, in main
    result = super().main(*args, **kwargs)
  File "[...]/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/_client.py", line 83, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/update.py", line 194, in update
    execute(client, output_file, output_paths=output_paths)
  File "[...]/renku/cli/_cwl.py", line 70, in execute
    process = factory.make(os.path.relpath(str(output_file)))
  File "[...]/cwltool/factory.py", line 58, in make
    load = load_tool.load_tool(cwl, self.loading_context)
  File "[...]/cwltool/load_tool.py", line 378, in load_tool
    loadingContext)
  File "[...]/cwltool/load_tool.py", line 346, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "[...]/renku/cli/_cwl.py", line 47, in construct_tool_object
    return workflow.default_make_tool(toolpath_object, *args, **kwargs)
  File "[...]/cwltool/workflow.py", line 54, in default_make_tool
    return Workflow(toolpath_object, loadingContext)
  File "[...]/cwltool/workflow.py", line 531, in __init__
    loadingContext.prov_obj))
  File "[...]/cwltool/workflow.py", line 619, in __init__
    toolpath_object["run"], loadingContext)
  File "[...]/cwltool/load_tool.py", line 378, in load_tool
    loadingContext)
  File "[...]/cwltool/load_tool.py", line 346, in make_tool
    tool = loadingContext.construct_tool_object(processobj, loadingContext)
  File "[...]/renku/cli/_cwl.py", line 47, in construct_tool_object
    return workflow.default_make_tool(toolpath_object, *args, **kwargs)
  File "[...]/cwltool/workflow.py", line 50, in default_make_tool
    return command_line_tool.CommandLineTool(toolpath_object, loadingContext)
  File "[...]/cwltool/command_line_tool.py", line 229, in __init__
    super(CommandLineTool, self).__init__(toolpath_object, loadingContext)
  File "[...]/cwltool/process.py", line 595, in __init__
    validate_js_expressions(cast(CommentedMap, toolpath_object), self.doc_schema.names[toolpath_object["class"]], validate_js_options)
  File "[...]/cwltool/validate_js.py", line 193, in validate_js_expressions
    expression_errors, _ = jshint_js(code_fragment_js, js_globals, jshint_options)
  File "[...]/cwltool/validate_js.py", line 118, in jshint_js
    context=jshint_functions_text
  File "[...]/cwltool/sandboxjs.py", line 161, in exec_js_process
    new_proc = new_js_proc(js_engine_code, force_docker_pull=force_docker_pull)
  File "[...]/cwltool/sandboxjs.py", line 110, in new_js_proc
    u"docker run node:slim".format(u", ".join(trynodes)))
cwltool.sandboxjs.JavascriptException: cwltool requires Node.js engine to evaluate and validate Javascript expressions, but couldn't find it.  Tried nodejs, node, docker run node:slim
```

**Comment by emmjab** [comment] 2019-11-25 15:59
Not sure if this is answering your question, but to see the lineage from the one file's point of view: https://renkulab.io/projects/1383/files/lineage/outputs/estimate.Rout

**Comment by rokroskar** [comment] 2019-11-25 16:26
Yes, that's for all three versions - we are not currently differentiating versions in the graph -- it's an improvement that is ongoing

**Comment by cchoirat** [comment] 2019-12-02 21:24
@rokroskar yes

**Comment by Panaetius** [comment] 2021-06-07 13:38
Looking at the error message, this is a duplicate of https://github.com/SwissDataScienceCenter/renku-python/issues/1983

**Closed by Panaetius** 2021-06-07 13:38 UTC
