### ISSUE TITLE
Bug while trying to migrate in the CLI

### ISSUE THREAD

**Issue by lusamino** [SwissDataScienceCenter/renku-python#1168] opened 2020-04-07 13:04 UTC
I was just trying to migrate a repo, and it just suddenly stopped and prompted the options to open an issue, and so I did 😄 I cannot comment more. I hope the traceback already give you some hints.

## Details
*Please verify and redact the details.*

**Renku version:** 0.10.2
**OS:** Darwin (Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64)
**Python:** 3.6.5

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/renku/core/models/jsonld.py", line 563, in from_yaml
    __source__=deepcopy(source)
  File "[...]/site-packages/renku/core/models/jsonld.py", line 544, in from_jsonld
    self = cls(**data_)
  File "<attrs generated init renku.core.models.datasets.Dataset>", line 46, in __init__
    self.__attrs_post_init__()
  File "[...]/site-packages/renku/core/models/datasets.py", line 588, in __attrs_post_init__
    dataset_file.path, revision='HEAD'
  File "[...]/site-packages/renku/core/management/repository.py", line 240, in find_previous_commit
    paths, revision
KeyError: 'Could not find a file .DS_Store in range HEAD'
```

## Additional context
Add any other context about the problem.

**Comment by jsam** [comment] 2020-04-08 17:20
Hey @lusamino, 

I've been trying to reproduce this now for a while with different version and I'm failing on all versions (0.10.0, 0.10.2 and latest master). The commit on which I'm executing the migration is this one `14c9cf99d0f779051018120470884f1bf81e5702` and also I'm executing on clean repository.

Here are a few things which you could try:

0) Try to re-setup virtual environment which contains renku installation (if you have it installed in venv)
1) Make sure that `.DS_Store` cache file is not in repository (and it's part of .gitignore)
2) Make sure to migrate on clean repository
3) Make sure you use renku>=0.10.2 

I could send you a PR with the migration to the repository you send me.

**Comment by mohammad-sdsc** [comment] 2020-04-09 09:47
Hi @lusamino 

I see that you were an early adopter of Renku 😄. It seems that there was a bug that would add ignored files to dataset's metadata without adding them to the Git.

You should be able to migrate using the following steps:
1. Make sure that you don't have any unsaved work in this project. Note that `git status` will show some changes because the migration operation did not complete successfully.
2. `git clean -dfx`
3. `git checkout .`
4. `renku migrate`

Your project should be migrated at this point.
One remaining issue is that `renku doctor` shows that three files are missing:
```
$ renku doctor
Please note that the diagnosis report is used to help Renku
maintainers with debugging if you file an issue. Use all proposed
solutions with maximal care and if in doubt ask an expert around or
file an issue. Thanks!

Warning: There are missing files in datasets.
        AB:
          .DS_Store
          1950/.DS_Store
          data/AB/metadata.yml
```

These files are not important but they still exists in the metadata (due to that bug). You can unlink them once a bug-fix in unlink command is merged. I'll ping you when it's done and tell you what to do.

**Comment by mohammad-sdsc** [comment] 2020-04-30 07:34
Hello again Luis!

The bug I mentioned above is fixed in renku CLI version `0.10.3`. Please upgrade to this version and follow the steps in my previous comment.
After that run the following command to remove missing files:
```
renku dataset unlink AB -I .DS_Store -I data/AB/metadata.yml
```
At this point, `renku doctor` should show that everything is OK with your project.

Cheers,
Mohammad

**Comment by rokroskar** [comment] 2020-05-07 10:01
Can we close this? @lusamino @mohammad-sdsc ?

**Comment by lusamino** [comment] 2020-05-11 14:35
Ohh, sorry guys, this just went to another folder in my inbox. Sure, please proceed :)

**Closed** 2020-05-11 15:20 UTC
