### ISSUE TITLE
Dataset export to Zenodo limited to 100MB

### ISSUE THREAD

**Issue by cmdoret** [SwissDataScienceCenter/renku-python#2984] opened 2022-06-30 11:04 UTC
Currently, dataset exports to Zenodo seem to be limited to 100Mb.
Attempting to export a larger dataset results in: 

```
$ renku dataset export saccer3-microc zenodo
...
Error: b'<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n
```
Example dataset: https://renkulab.io/projects/cyril.matthey-doret/sequence-loopability/datasets/saccer3-microc/

In most practical scenarios, the datasets will be larger than this.
Is it a limitation of the Zenodo API or would it be possible to remove this limitation on our side ?

**Comment by Panaetius** [comment] 2022-07-05 06:47
Duplicate of https://github.com/SwissDataScienceCenter/renku-python/issues/717 it is a Zenodo issue and they still haven't published their new, promised API

**Closed by Panaetius** 2022-07-05 06:47 UTC
